lint:
  files_exist:
    - conf/modules.config
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
  modules_config: false
  nf_test_content: false
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: "@maxulysse"
  description: Generate Panel of Normals, models or other similar references from lots of samples
  force: false
  is_nfcore: true
  name: createpanelrefs
  org: nf-core
  outdir: .
  version: 1.0.0
