lint:
  files_exist:
    - conf/modules.config
  modules_config: false
  nf_test_content: false
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: "@maxulysse"
  description: Generate Panel of Normals, models or other similar references from
    lots of samples
  force: false
  is_nfcore: true
  name: createpanelrefs
  org: nf-core
  outdir: .
  version: 1.0.0
