lint:
  files_exist:
    - conf/modules.config
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
  modules_config: false
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: "@maxulysse"
  description: Generate Panel of Normals, models or other similar references from
    lots of samples
  force: false
  is_nfcore: true
  name: createpanelrefs
  org: nf-core
  outdir: .
  version: 1.0.0
